baseURL = 'https://maxwellgriffith345.github.io/'
languageCode = 'en-us'
title = 'Maxwell Griffith'
theme = 'ananke'


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true

[markup.goldmark.renderer]
  unsafe=true #A
